'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { apiFetch } from '@/lib/api';
import { AppShell } from './app-shell';
type Stats = { users: number; active: number; newToday: number; newWeek: number; sources: number; clips: number; reframeOutputs: number; genToday: number; genWeek: number; genTotal: number; success: number; failed: number; processing: number; exports: number; recentUsers: Array<{ id: string; email: string; displayName: string }>; recentGenerations: Array<{ id: string; operation: string; status: string; user: { email: string }; createdAt: string }>; recentFailures: Array<{ id: string; error: string | null; clipRenderError: string | null }>; daily: Array<{ day: string; generations: number; users: number }> };
export function AdminDashboard() {
  const [stats, setStats] = useState<(Stats & { modes: Array<{ aiMode: string; _count: number }>; styles: Array<{ templateId: string | null; _count: number }>; trackedStorageBytes: number; storageNote: string }) | null>(null); const [error, setError] = useState('');
  useEffect(() => { let alive = true; const load = () => void apiFetch<NonNullable<typeof stats>>('/admin/stats').then(v => { if (alive) { setStats(v); setError(''); } }).catch(e => { if (alive) setError(e.message); }); load(); const t = setInterval(load, 20000); return () => { alive = false; clearInterval(t); }; }, []);
  const cards = stats ? [['Total users', stats.users], ['Active accounts', stats.active], ['New users today', stats.newToday], ['New users this week', stats.newWeek], ['Source videos', stats.sources], ['Generated clips', stats.clips], ['Quick Reframe outputs', stats.reframeOutputs], ['Exported videos', stats.exports], ['Generations today', stats.genToday], ['Generations this week', stats.genWeek], ['Generations total', stats.genTotal], ['Successful jobs', stats.success], ['Failed / refunded', stats.failed], ['Currently processing', stats.processing]] : [];
  return <AppShell><div className='flex flex-wrap items-end justify-between gap-4'><div><p className='eyebrow'>Owner workspace</p><h1 className='mt-2 font-display text-3xl font-bold'>Admin</h1><p className='mt-2 text-sm text-muted-foreground'>Account activity and generation health · dates in UTC</p></div><Link href='/admin/users' className='btn-primary rounded-xl px-5 py-3'>Manage users</Link></div>
    {error && <p role='alert' className='mt-5 text-danger'>{error}</p>}{!stats && !error && <p className='mt-6'>Loading activity…</p>}
    <div className='mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4'>{cards.map(([label, value]) => <div key={label} className='rounded-2xl border border-border bg-surface p-4'><p className='text-xs text-muted-foreground'>{label}</p><p className='mt-3 font-display text-3xl font-bold tabular-nums'>{value}</p></div>)}</div>
    {stats && <><div className='mt-6 grid gap-5 lg:grid-cols-2'>{(['generations', 'users'] as const).map(field => <section key={field} className='rounded-2xl border border-border bg-surface p-5'><h2 className='font-display text-lg font-semibold'>{field === 'generations' ? 'Generations by day' : 'New users by day'}</h2><div className='mt-5 flex h-40 items-end gap-3'>{stats.daily.map(d => <div key={d.day} className='flex h-full min-w-0 flex-1 flex-col justify-end gap-2 text-center text-xs'><span className='text-soft'>{d[field]}</span><div className={field === 'generations' ? 'rounded-t-lg bg-primary' : 'rounded-t-lg bg-secondary'} style={{ height: `${Math.max(2, d[field] / Math.max(1, ...stats.daily.map(v => v[field])) * 100)}px` }}/><span className='text-muted-foreground'>{d.day.slice(5)}</span></div>)}</div></section>)}</div>
      <div className='mt-6 grid gap-5 lg:grid-cols-3'>{[
        { title: 'Generation outcomes', rows: [{ label: 'Successful', count: stats.success }, { label: 'Failed / refunded', count: stats.failed }, { label: 'Processing', count: stats.processing }] },
        { title: 'Processing modes', rows: stats.modes.map(m => ({ label: m.aiMode === 'FALLBACK_ONLY' ? 'XeeFree' : m.aiMode === 'ONLINE' ? 'XeePro' : m.aiMode, count: m._count })) },
        { title: 'Generated clip styles', rows: stats.styles.map(s => ({ label: s.templateId === 'AUTOMATIC_1' ? 'StyleZero' : s.templateId === 'AUTOMATIC_2' ? 'StyleOne' : s.templateId === 'AUTOMATIC_3_STYLE_TWO' ? 'StyleTwo' : s.templateId === 'AUTOMATIC_RAW' ? 'No Edit' : 'Other / legacy', count: s._count })) }
      ].map(chart => <section key={chart.title} className='rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold'>{chart.title}</h2><div className='mt-4 grid gap-3'>{chart.rows.map(row => <div key={row.label}><p className='flex justify-between gap-3 text-xs text-soft'><span>{row.label}</span><span>{row.count}</span></p><div className='mt-2 h-2 rounded bg-muted'><div className='h-2 rounded bg-primary' style={{ width: `${row.count / Math.max(1, ...chart.rows.map(v => v.count)) * 100}%` }}/></div></div>)}</div></section>)}</div>
      <p className='mt-5 text-xs text-muted-foreground'>Tracked media: {(stats.trackedStorageBytes / 1073741824).toFixed(2)} GiB. {stats.storageNote} Mode counts include analysis jobs; style counts measure generated clips. Generation outcomes cover requests tracked since accounts launched.</p>
      <div className='mt-6 grid gap-5 pb-10 lg:grid-cols-3'><section className='rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold'>Recent users</h2><div className='mt-4 grid gap-3'>{stats.recentUsers.map(u => <Link key={u.id} href={'/admin/users/detail?id=' + u.id} className='break-all text-sm text-primary-soft'>{u.displayName || u.email}<span className='block text-xs text-muted-foreground'>{u.email}</span></Link>)}</div></section>
      <section className='rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold'>Recent generations</h2><div className='mt-4 grid gap-3'>{stats.recentGenerations.map(g => <div key={g.id} className='text-sm'><p className='break-all'>{g.user.email}</p><p className='text-xs text-muted-foreground'>{g.operation === 'QUICK_REFRAME' ? 'Quick Reframe' : 'Create Clips'} · {g.status.toLowerCase()}</p></div>)}</div></section>
      <section className='rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold'>Recent failures</h2><div className='mt-4 grid gap-3'>{stats.recentFailures.length ? stats.recentFailures.map(f => <p key={f.id} className='break-words text-sm text-soft'>{f.clipRenderError || f.error || 'Processing failed'}</p>) : <p className='text-sm text-muted-foreground'>No failures recorded.</p>}</div></section></div></>}
  </AppShell>;
}
