'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { apiFetch } from '@/lib/api';
import { AppShell } from './app-shell';
import { ConfirmDialog } from './ui/confirm-dialog';
type Detail = { user: { email: string; displayName: string; creditBalance: number; creditsConsumed: number; status: string; createdAt: string; lastLoginAt: string | null }; ledger: Array<{ id: string; amount: number; type: string; reason: string; createdAt: string }>; audit: Array<{ id: string; action: string; reason: string | null; createdAt: string }>; generations: Array<{ id: string; status: string; clipRenderStatus: string | null; createdAt: string }>; quickReframe: Array<{ id: string; status: string; createdAt: string }>; failures: Array<{ id: string; error: string | null; clipRenderError: string | null }> };
export function AdminUserDetail() {
  const [id, setId] = useState(''); const [data, setData] = useState<Detail | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [confirm, setConfirm] = useState(false);
  const [mode, setMode] = useState('ADD'); const [amount, setAmount] = useState(5); const [reason, setReason] = useState('');
  useEffect(() => { setId(new URLSearchParams(window.location.search).get('id') ?? ''); }, []);
  const load = async () => { setData(await apiFetch<Detail>('/admin/users/' + encodeURIComponent(id))); };
  useEffect(() => { if (id) void load().catch(e => setError(e.message)); }, [id]);
  async function action(path: string, body: unknown) { setBusy(true); setError(''); try { await apiFetch('/admin/users/' + encodeURIComponent(id) + '/' + path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); await load(); setConfirm(false); } catch (e) { setError(e instanceof Error ? e.message : 'Please try again.'); } finally { setBusy(false); } }
  return <AppShell><Link href='/admin/users' className='text-primary-soft'>← Users</Link><h1 className='mt-3 break-all font-display text-2xl font-bold'>{data?.user.email ?? 'User account'}</h1>{error && <p role='alert' className='mt-4 text-danger'>{error}</p>}
    {data && <><div className='mt-6 grid gap-5 lg:grid-cols-2'><section className='grid gap-4 rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold'>Account</h2><p>{data.user.displayName || 'No name set'} · {data.user.status.toLowerCase()}</p><p className='text-3xl font-bold'>{data.user.creditBalance} <span className='text-base font-normal text-muted-foreground'>credits remaining</span></p><p className='text-sm text-soft'>{data.user.creditsConsumed} credits consumed</p><p className='text-xs text-muted-foreground'>Created {new Date(data.user.createdAt).toLocaleString()}<br/>Last login {data.user.lastLoginAt ? new Date(data.user.lastLoginAt).toLocaleString() : '—'}</p><button disabled={busy} onClick={() => void action(data.user.status === 'ACTIVE' ? 'suspend' : 'reactivate', { reason })} className='min-h-11 rounded-xl border border-border px-4'>{data.user.status === 'ACTIVE' ? 'Suspend user' : 'Reactivate user'}</button></section>
      <section className='grid content-start gap-4 rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold'>Manage credits</h2><label className='grid gap-2 text-sm'>Action<select value={mode} onChange={e => setMode(e.target.value)} className='rounded-xl border border-border bg-inset p-3'><option value='ADD'>Add credits</option><option value='REMOVE'>Remove credits</option><option value='SET'>Set exact balance</option></select></label><label className='grid gap-2 text-sm'>Credits<input type='number' min={0} max={1000000} value={amount} onChange={e => setAmount(Number(e.target.value))} className='rounded-xl border border-border bg-inset p-3'/></label><label className='grid gap-2 text-sm'>Reason (optional)<input value={reason} maxLength={500} onChange={e => setReason(e.target.value)} className='rounded-xl border border-border bg-inset p-3'/></label><button disabled={busy || !Number.isSafeInteger(amount) || amount < 0} onClick={() => setConfirm(true)} className='btn-primary min-h-11 rounded-xl'>Review credit change</button></section></div>
      <section className='mt-6 overflow-x-auto rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold'>Credit ledger · latest 100</h2><table className='mt-4 w-full text-left text-sm'><thead className='text-muted-foreground'><tr><th className='p-2'>Date</th><th className='p-2'>Action</th><th className='p-2'>Change</th><th className='p-2'>Reason</th></tr></thead><tbody>{data.ledger.map(l => <tr key={l.id} className='border-t border-border'><td className='whitespace-nowrap p-2'>{new Date(l.createdAt).toLocaleString()}</td><td className='p-2'>{l.type.toLowerCase().replaceAll('_', ' ')}</td><td className='p-2 tabular-nums'>{l.amount > 0 ? '+' : ''}{l.amount}</td><td className='p-2'>{l.reason}</td></tr>)}</tbody></table></section>
      <div className='my-6 grid gap-5 lg:grid-cols-3'><section className='rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold'>Generation history</h2>{data.generations.map(g => <p key={g.id} className='mt-3 text-sm text-soft'>{new Date(g.createdAt).toLocaleDateString()} · {g.clipRenderStatus || g.status}</p>)}</section><section className='rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold'>Quick Reframe history</h2>{data.quickReframe.map(g => <p key={g.id} className='mt-3 text-sm text-soft'>{new Date(g.createdAt).toLocaleDateString()} · {g.status}</p>)}</section><section className='rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold'>Recent failures</h2>{data.failures.map(f => <p key={f.id} className='mt-3 text-sm text-soft'>{f.clipRenderError || f.error}</p>)}</section></div><section className='mb-10 rounded-2xl border border-border bg-surface p-5'><h2 className='font-semibold'>Admin audit log</h2>{data.audit.map(a => <p key={a.id} className='mt-3 text-sm text-soft'>{new Date(a.createdAt).toLocaleString()} · {a.action.toLowerCase().replaceAll('_', ' ')} · {a.reason}</p>)}</section>
      <ConfirmDialog open={confirm} title='Confirm credit change' description={`${mode === 'SET' ? 'Set balance to' : mode === 'REMOVE' ? 'Remove' : 'Add'} ${amount} credits for ${data.user.email}? Current balance: ${data.user.creditBalance}.`} confirmLabel='Confirm change' busy={busy} onConfirm={() => void action('credits', { mode, amount, reason })} onCancel={() => setConfirm(false)}/>
    </>}
  </AppShell>;
}
