'use client';

import { Copy, Layers, Trash2 } from 'lucide-react';
import type { ManualEditCommand } from '@/lib/edit-mode-api';
import type { EditAsset, EditElement, EditProject } from '@/lib/edit-mode-types';

const num = (value: unknown, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const fieldClass = 'w-full rounded-lg border border-white/10 bg-black/20 px-2 py-1.5 text-xs text-slate-200';

export function EditInspector({ project, source, selected, onPreview, onCommit, onDebounced,
  onDuplicate, onDelete }: { project: EditProject; source?: EditAsset; selected?: EditElement;
  onPreview: (element: EditElement) => void; onCommit: (command: ManualEditCommand) => void;
  onDebounced: (command: ManualEditCommand) => void; onDuplicate: () => void; onDelete: () => void;
}) {
  if (!selected) return <section className='rounded-2xl border border-white/10 bg-[#0d111c] p-4'><h2 className='text-sm font-semibold'>Inspector</h2><p className='mt-3 text-xs text-slate-500'>Select an element in the timeline or preview.</p><p className='mt-4 text-[11px] text-slate-600'>Revision {project.revision}</p></section>;
  if (selected.type === 'VIDEO') return <section className='rounded-2xl border border-violet-300/20 bg-[#0d111c] p-4'><div className='flex items-center justify-between'><h2 className='text-sm font-semibold'>Selected segment</h2><span className='rounded-full bg-violet-400/10 px-2 py-1 text-[10px] font-semibold text-violet-200'>VIDEO</span></div><dl className='mt-4 grid gap-2 text-xs'>{[['Timeline start', `${selected.startTime.toFixed(2)}s`], ['Timeline duration', `${selected.duration.toFixed(2)}s`], ['Source trim start', `${selected.trimStart.toFixed(2)}s`], ['Source trim end', `${(selected.trimEnd ?? selected.trimStart + selected.duration).toFixed(2)}s`], ['Source asset', source?.originalName ?? 'Unknown']].map(([label, value]) => <div key={label} className='flex justify-between gap-4 rounded-lg bg-white/[.03] px-3 py-2'><dt className='text-slate-500'>{label}</dt><dd className='truncate text-right text-slate-200'>{value}</dd></div>)}</dl></section>;
  const p = selected.properties;
  const patchProperties = (patch: Record<string, unknown>) => onPreview({ ...selected, properties: { ...p, ...patch } });
  const timing = (patch: Partial<Pick<EditElement, 'startTime' | 'duration' | 'trimStart' | 'trimEnd'>>) => onPreview({ ...selected, ...patch });
  const commitTiming = () => onCommit({ action: 'set-element-timing', elementId: selected.id,
    startTime: selected.startTime, duration: selected.duration, trimStart: selected.trimStart,
    ...(selected.trimEnd == null ? {} : { trimEnd: selected.trimEnd }) });
  const textCommand = (properties = selected.properties): ManualEditCommand => ({ action: 'update-text',
    elementId: selected.id, content: String(properties.content ?? ''),
    fontSize: num(properties.fontSize, 48), fontWeight: num(properties.fontWeight, 700),
    fontFamily: String(properties.fontFamily ?? 'Arial, sans-serif'),
    color: String(properties.color ?? '#ffffff'),
    textAlign: (properties.textAlign as 'left' | 'center' | 'right') ?? 'center' });
  return <section className='rounded-2xl border border-cyan-300/20 bg-[#0d111c] p-4'>
    <div className='flex items-center justify-between'><h2 className='text-sm font-semibold'>Inspector</h2><span className='rounded-full bg-cyan-400/10 px-2 py-1 text-[10px] font-semibold text-cyan-200'>{selected.type === 'IMAGE' ? String(p.role ?? 'IMAGE') : selected.type}</span></div>
    <div className='mt-4 grid grid-cols-2 gap-2'><label className='text-[10px] text-slate-500'>Start<input className={fieldClass} type='number' min={0} step='.05' value={selected.startTime} onChange={(e) => timing({ startTime: num(e.target.value) })} onBlur={commitTiming} /></label><label className='text-[10px] text-slate-500'>Duration<input className={fieldClass} type='number' min='.05' step='.05' value={selected.duration} onChange={(e) => timing({ duration: num(e.target.value) })} onBlur={commitTiming} /></label></div>
    {(selected.type === 'IMAGE' || selected.type === 'TEXT') && <>
      <div className='mt-3 grid grid-cols-2 gap-2'>{(['x', 'y', 'width', 'height'] as const).map((key) => <label key={key} className='text-[10px] capitalize text-slate-500'>{key}<input className={fieldClass} type='number' min={0} max={1} step='.01' value={num(p[key])} onChange={(e) => patchProperties({ [key]: num(e.target.value) })} onBlur={() => onCommit(key === 'x' || key === 'y' ? { action: 'move-element', elementId: selected.id, x: num(selected.properties.x), y: num(selected.properties.y) } : { action: 'resize-element', elementId: selected.id, width: num(selected.properties.width), height: num(selected.properties.height) })} /></label>)}</div>
      <label className='mt-3 block text-[10px] text-slate-500'>Opacity · {Math.round(num(p.opacity, 1) * 100)}%<input className='mt-1 w-full accent-cyan-300' type='range' min={0} max={1} step='.01' value={num(p.opacity, 1)} onChange={(e) => patchProperties({ opacity: num(e.target.value) })} onPointerUp={() => onCommit({ action: 'set-element-opacity', elementId: selected.id, opacity: num(selected.properties.opacity, 1) })} /></label>
      <div className='mt-3'><p className='text-[10px] text-slate-500'>Layer</p><div className='mt-1 grid grid-cols-4 gap-1'>{[['Back', -1000], ['−', -1], ['+', 1], ['Front', 1000]].map(([label, delta]) => <button key={label} onClick={() => onCommit({ action: 'set-element-z-index', elementId: selected.id, zIndex: Math.max(0, num(p.zIndex) + Number(delta)) })} className='rounded border border-white/10 py-1 text-[10px]'><Layers size={10} className='mx-auto' />{label}</button>)}</div></div>
    </>}
    {selected.type === 'TEXT' && <div className='mt-3 grid gap-2'>
      <label className='text-[10px] text-slate-500'>Content<textarea className={`${fieldClass} min-h-20 resize-y`} value={String(p.content ?? '')} onChange={(e) => { const next = { ...p, content: e.target.value }; patchProperties(next); onDebounced(textCommand(next)); }} /></label>
      <div className='grid grid-cols-2 gap-2'><label className='text-[10px] text-slate-500'>Size<input className={fieldClass} type='number' min={8} max={300} value={num(p.fontSize, 48)} onChange={(e) => patchProperties({ fontSize: num(e.target.value) })} onBlur={() => onCommit(textCommand())} /></label><label className='text-[10px] text-slate-500'>Weight<select className={fieldClass} value={num(p.fontWeight, 700)} onChange={(e) => { const next = { ...p, fontWeight: num(e.target.value) }; patchProperties(next); onCommit(textCommand(next)); }}><option value={400}>Regular</option><option value={600}>Semibold</option><option value={700}>Bold</option><option value={800}>Extra bold</option></select></label></div>
      <div className='grid grid-cols-2 gap-2'><label className='text-[10px] text-slate-500'>Font<select className={fieldClass} value={String(p.fontFamily ?? 'Arial, sans-serif')} onChange={(e) => { const next = { ...p, fontFamily: e.target.value }; patchProperties(next); onCommit(textCommand(next)); }}><option value='Arial, sans-serif'>Arial</option><option value='Georgia, serif'>Georgia</option><option value='monospace'>Monospace</option></select></label><label className='text-[10px] text-slate-500'>Align<select className={fieldClass} value={String(p.textAlign ?? 'center')} onChange={(e) => { const next = { ...p, textAlign: e.target.value }; patchProperties(next); onCommit(textCommand(next)); }}><option value='left'>Left</option><option value='center'>Center</option><option value='right'>Right</option></select></label></div>
      <label className='text-[10px] text-slate-500'>Color<input className='mt-1 h-8 w-full rounded bg-transparent' type='color' value={String(p.color ?? '#ffffff')} onChange={(e) => patchProperties({ color: e.target.value })} onBlur={() => onCommit(textCommand())} /></label>
    </div>}
    {selected.type === 'AUDIO' && <div className='mt-3 grid gap-3'><label className='text-[10px] text-slate-500'>Volume · {Math.round(num(p.volume, .25) * 100)}%<input className='mt-1 w-full accent-emerald-300' type='range' min={0} max={1} step='.01' value={num(p.volume, .25)} onChange={(e) => patchProperties({ volume: num(e.target.value) })} onPointerUp={() => onCommit({ action: 'set-audio-volume', elementId: selected.id, volume: num(selected.properties.volume, .25) })} /></label><label className='flex items-center gap-2 text-xs'><input type='checkbox' checked={Boolean(p.muted)} onChange={(e) => { patchProperties({ muted: e.target.checked }); onCommit({ action: 'set-audio-muted', elementId: selected.id, muted: e.target.checked }); }} />Muted</label><div className='grid grid-cols-2 gap-2'>{(['fadeInSec', 'fadeOutSec'] as const).map((key) => <label key={key} className='text-[10px] text-slate-500'>{key === 'fadeInSec' ? 'Fade in' : 'Fade out'}<input className={fieldClass} type='number' min={0} step='.1' value={num(p[key])} onChange={(e) => patchProperties({ [key]: num(e.target.value) })} onBlur={() => onCommit({ action: 'set-audio-fade', elementId: selected.id, fadeInSec: num(selected.properties.fadeInSec), fadeOutSec: num(selected.properties.fadeOutSec) })} /></label>)}</div><div className='grid grid-cols-2 gap-2'><label className='text-[10px] text-slate-500'>Trim start<input className={fieldClass} type='number' min={0} step='.05' value={selected.trimStart} onChange={(e) => timing({ trimStart: num(e.target.value), trimEnd: num(e.target.value) + selected.duration })} onBlur={commitTiming} /></label><label className='text-[10px] text-slate-500'>Trim end<input className={fieldClass} type='number' min='.05' step='.05' value={selected.trimEnd ?? selected.trimStart + selected.duration} onChange={(e) => timing({ trimEnd: num(e.target.value), duration: num(e.target.value) - selected.trimStart })} onBlur={commitTiming} /></label></div></div>}
    <div className='mt-4 flex gap-2'><button onClick={onDuplicate} className='flex flex-1 items-center justify-center gap-1 rounded-lg border border-white/10 py-2 text-xs'><Copy size={13} />Duplicate</button><button onClick={onDelete} className='flex flex-1 items-center justify-center gap-1 rounded-lg border border-red-400/20 py-2 text-xs text-red-300'><Trash2 size={13} />Delete</button></div>
  </section>;
}
