ALTER TABLE "ClipCandidate"
  ADD COLUMN "decisionSource" TEXT NOT NULL DEFAULT 'DETERMINISTIC_FALLBACK',
  ADD COLUMN "openingStrength" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "endingStrength" DOUBLE PRECISION NOT NULL DEFAULT 0;
