import { expect, test } from '@playwright/test';
test('public Quick Reframe plays a real export and resumes from History',async({page})=>{
  test.skip(!process.env.REFRAME_LIVE_ID,'Requires a disposable completed Quick Reframe session.');
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`/quick-reframe?video=${process.env.REFRAME_LIVE_ID}`);
  await expect(page.getByRole('heading',{name:'Quick Reframe AI'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Clean original',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'Clean original',exact:true}).click();
  await expect.poll(()=>page.locator('video').first().evaluate((v:HTMLVideoElement)=>v.readyState)).toBeGreaterThanOrEqual(2);
  await expect(page.getByRole('button',{name:'StyleOne',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'StyleOne',exact:true}).click();
  const video=page.locator('video').nth(1);
  await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.readyState)).toBeGreaterThanOrEqual(2);
  await video.evaluate((v:HTMLVideoElement)=>{v.muted=true;return v.play();});
  await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeGreaterThan(.2);
  await video.evaluate((v:HTMLVideoElement)=>v.pause());
  expect(await video.evaluate(v=>getComputedStyle(v.parentElement!).aspectRatio)).toBe('9 / 16');
  await page.screenshot({path:'test-results/quick-reframe-styleone.png',fullPage:true});
  await page.getByRole('button',{name:'Compare',exact:true}).click();
  await expect(page.getByLabel('Before / After comparison')).toBeVisible();
  await page.getByRole('link',{name:'Open History',exact:true}).click();
  const section=page.getByRole('region',{name:'Quick Reframe history'});
  const card=section.locator('article').filter({hasText:'spoken-tip.mp4'});
  await expect(card.getByRole('link',{name:'Re-edit',exact:true})).toBeVisible();
  await card.getByRole('link',{name:'Re-edit',exact:true}).click();
  await expect(page.getByRole('button',{name:'Export Video',exact:true})).toBeVisible();
  await page.reload();await expect(page.getByRole('button',{name:'StyleOne',exact:true})).toBeEnabled();
  await page.setViewportSize({width:375,height:812});
  await page.getByRole('button',{name:'Captions',exact:true}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByLabel('Caption 1',{exact:true})).toBeVisible();
  await page.keyboard.press('Escape');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.screenshot({path:'test-results/quick-reframe-public.png',fullPage:true});
  expect(errors).toEqual([]);
});
