ALTER TYPE "ProcessingStage" ADD VALUE IF NOT EXISTS 'MULTIMODAL_UNDERSTANDING';
ALTER TYPE "ProcessingStage" ADD VALUE IF NOT EXISTS 'EVIDENCE_FUSION';
ALTER TYPE "ProcessingStage" ADD VALUE IF NOT EXISTS 'CLIP_UNDERSTANDING';
ALTER TYPE "ProcessingStage" ADD VALUE IF NOT EXISTS 'CONTENT_GENERATION';
ALTER TYPE "ProcessingStage" ADD VALUE IF NOT EXISTS 'CRITIC_VALIDATION';

ALTER TABLE "ClipCandidate"
  ADD COLUMN "generationQuality" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "confidence" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "evidence" JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN "clipUnderstanding" JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN "criticResult" JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN "providerMetadata" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN "creativeCandidates" JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN "generationMode" TEXT NOT NULL DEFAULT 'DETERMINISTIC_FALLBACK',
  ADD COLUMN "fallbackUsed" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "failureCategory" TEXT NOT NULL DEFAULT '';

ALTER TABLE "TranscriptSegment"
  ADD COLUMN "words" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN "confidence" DOUBLE PRECISION,
  ADD COLUMN "speaker" TEXT;
